# Generated by Django 5.2.17 on 2026-09-28 17:30

from django.db import migrations, models

import identity.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "user_id",
                    models.CharField(
                        default=identity.models.generate_user_id,
                        editable=False,
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("LICENSEE", "Licensee"),
                            ("PERSONNEL", "Authorised Personnel"),
                            ("LICENSING_AUTHORITY", "Licensing Authority"),
                            ("SOFTWARE_OWNER", "Software Owner"),
                            ("HEAD_AUTHORITY", "Head Authority"),
                        ],
                        max_length=32,
                    ),
                ),
                ("contact_encrypted", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("failed_login_count", models.PositiveSmallIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "role__in",
                                [
                                    "LICENSEE",
                                    "PERSONNEL",
                                    "LICENSING_AUTHORITY",
                                    "SOFTWARE_OWNER",
                                    "HEAD_AUTHORITY",
                                ],
                            )
                        ),
                        name="user_role_valid",
                    )
                ],
            },
        ),
    ]
