# Generated by Django 5.2.17 on 2026-09-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0003_otpchallenge"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="otpchallenge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("closed_at__isnull", True)),
                fields=("user", "purpose"),
                name="one_open_otp_per_user_and_purpose",
            ),
        ),
    ]
