# Generated by Django 5.2.17 on 2026-09-29 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0004_otp_one_open_per_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpchallenge",
            name="subject",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="otpchallenge",
            name="purpose",
            field=models.CharField(
                choices=[("LOGIN", "Login second factor"), ("ENROL", "Licence-gated enrolment")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="otpchallenge",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="otp_challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="otpchallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("subject", ""), ("user__isnull", False)),
                    models.Q(("user__isnull", True), models.Q(("subject", ""), _negated=True)),
                    _connector="OR",
                ),
                name="otp_user_xor_subject",
            ),
        ),
    ]
