# Generated by Django 5.2.17 on 2026-09-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0005_otp_subject"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="otpchallenge",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("closed_at__isnull", True), models.Q(("subject", ""), _negated=True)
                ),
                fields=("subject", "purpose"),
                name="one_open_otp_per_subject_and_purpose",
            ),
        ),
    ]
