# Generated by Django 5.2.17 on 2026-09-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0006_otp_one_open_per_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="licensee_gstin_index",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
