# Generated by Django 5.2.17 on 2026-09-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0007_user_licensee_gstin_index"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("licensee_gstin_index", ""), _negated=True),
                fields=("licensee_gstin_index",),
                name="one_account_per_licensee_gstin",
            ),
        ),
    ]
