# Generated by Django 5.2.17 on 2026-10-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0008_one_account_per_licensee_gstin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpchallenge",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login second factor"),
                    ("ENROL", "Licence-gated enrolment"),
                    ("DECISION", "Signing a decision"),
                ],
                max_length=16,
            ),
        ),
    ]
