# Generated by Django 5.2.17 on 2026-10-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0009_otp_purpose_decision"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_index",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email_index", ""), _negated=True),
                fields=("email_index",),
                name="one_account_per_email",
            ),
        ),
    ]
