# Generated by Django 5.2.17 on 2026-10-01 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogue", "0004_rule_validity_positive"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("gstin_index", models.CharField(max_length=64)),
                ("delta", models.DecimalField(decimal_places=3, max_digits=14)),
                ("balance_after", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("OPENING", "Opening balance"),
                            ("TRANSACTION", "Approved transaction"),
                        ],
                        max_length=16,
                    ),
                ),
                ("transaction_reference", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalogue.substance"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("gstin_index", models.CharField(max_length=64)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalogue.substance"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("gstin_index", "substance"),
                        name="one_balance_per_business_and_substance",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 0)), name="stock_never_negative"
                    ),
                ],
            },
        ),
    ]
