# Generated by Django 5.2.17 on 2026-10-03 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("positions", "0002_one_position_per_area"),
        ("reasons", "0002_seed_defaults"),
        ("transactions", "0003_superintendent_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("BUYER_REJECTION", "Buyer rejected a transaction"),
                            ("SUPERINTENDENT_FLAG", "Superintendent flagged a transaction"),
                        ],
                        max_length=24,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("pattern_count", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="positions.position",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="reasons.reasoncode"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alerts",
                        to="transactions.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlertAcknowledgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("user_id", models.CharField(max_length=12)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acknowledgement",
                        to="alerts.authorityalert",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="authorityalert",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["BUYER_REJECTION", "SUPERINTENDENT_FLAG"])),
                name="alert_kind_valid",
            ),
        ),
    ]
