# Generated by Django 5.2.17 on 2026-09-29 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogue", "0004_rule_validity_positive"),
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Licence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number_encrypted", models.TextField()),
                ("number_index", models.CharField(max_length=64, unique=True)),
                ("gstin_encrypted", models.TextField()),
                ("gstin_index", models.CharField(db_index=True, max_length=64)),
                ("holder_name", models.CharField(max_length=200)),
                ("contact_encrypted", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="positions.area"
                    ),
                ),
                (
                    "licence_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalogue.licencetype"
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogue.substance",
                    ),
                ),
                (
                    "substance_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogue.substanceclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LicencePermissionsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("may_buy", models.BooleanField()),
                ("may_sell", models.BooleanField()),
                ("may_transport", models.BooleanField()),
                ("max_stock_qty", models.DecimalField(decimal_places=3, max_digits=12)),
                ("max_per_transaction_qty", models.DecimalField(decimal_places=3, max_digits=12)),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
                (
                    "licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="permission_snapshots",
                        to="licensing.licence",
                    ),
                ),
                (
                    "rule_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogue.licencetyperuleversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LicenceValidityPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("recorded_by", models.CharField(max_length=64)),
                (
                    "licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validity_periods",
                        to="licensing.licence",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="licence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("substance__isnull", False), ("substance_class__isnull", True)),
                    models.Q(("substance__isnull", True), ("substance_class__isnull", False)),
                    _connector="OR",
                ),
                name="licence_exactly_one_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="licencevalidityperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_on__gte", models.F("starts_on"))),
                name="period_ends_after_start",
            ),
        ),
    ]
