# Generated by Django 5.2.17 on 2026-09-29 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0004_rule_validity_positive"),
        ("licensing", "0003_status_only_updates"),
    ]

    operations = [
        migrations.AddField(
            model_name="licencepermissionssnapshot",
            name="substance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogue.substance",
            ),
        ),
    ]
