# Generated by Django 5.2.17 on 2026-09-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0004_rule_validity_positive"),
        ("licensing", "0004_snapshot_substance"),
        ("positions", "0002_one_position_per_area"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="licence",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["ACTIVE", "SUSPENDED", "REVOKED"])),
                name="licence_status_valid",
            ),
        ),
    ]
