# Generated by Django 5.2.17 on 2026-10-03 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("positions", "0002_one_position_per_area"),
        ("transactions", "0004_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="OversightBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="positions.position",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="oversight.oversightbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SuperintendentSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("period_days", models.PositiveSmallIntegerField()),
                ("starts_on", models.DateField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(max_length=64)),
                (
                    "position",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_setting",
                        to="positions.position",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="oversightbatch",
            constraint=models.UniqueConstraint(
                fields=("position", "period_start"), name="one_batch_per_period"
            ),
        ),
        migrations.AddConstraint(
            model_name="oversightbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="batch_period_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="batchitem",
            constraint=models.UniqueConstraint(
                fields=("batch", "transaction"), name="one_item_per_transaction"
            ),
        ),
        migrations.AddConstraint(
            model_name="superintendentsetting",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_days__in", (15, 30, 60))), name="review_period_valid"
            ),
        ),
    ]
