"""Flags and sign-offs: readable wherever their batch/item is readable; only SYSTEM writes;
append-only (even for the table owner)."""

# Generated by Django 5.2.17 on 2026-10-03 06:23

import django.db.models.deletion
from django.db import migrations, models

ROLE = "current_setting('app.role', true)"


def _append_only(table: str, prefix: str) -> str:
    return f"""
REVOKE UPDATE, DELETE, TRUNCATE ON {table} FROM gj_app;
CREATE TRIGGER {prefix}_no_update_delete BEFORE UPDATE OR DELETE ON {table}
    FOR EACH ROW EXECUTE FUNCTION reject_append_only_change();
CREATE TRIGGER {prefix}_no_truncate BEFORE TRUNCATE ON {table}
    FOR EACH STATEMENT EXECUTE FUNCTION reject_append_only_change();
"""


FORWARD = f"""
ALTER TABLE oversight_batchflag ENABLE ROW LEVEL SECURITY;
CREATE POLICY flag_read ON oversight_batchflag FOR SELECT TO gj_app
    USING (item_id IN (SELECT id FROM oversight_batchitem));
CREATE POLICY flag_insert ON oversight_batchflag FOR INSERT TO gj_app
    WITH CHECK ({ROLE} = 'SYSTEM');
{_append_only("oversight_batchflag", "flag")}
ALTER TABLE oversight_batchsignoff ENABLE ROW LEVEL SECURITY;
CREATE POLICY signoff_read ON oversight_batchsignoff FOR SELECT TO gj_app
    USING (batch_id IN (SELECT id FROM oversight_oversightbatch));
CREATE POLICY signoff_insert ON oversight_batchsignoff FOR INSERT TO gj_app
    WITH CHECK ({ROLE} = 'SYSTEM');
{_append_only("oversight_batchsignoff", "signoff")}
"""  # noqa: S608 - SQL built only from constants; no user input.

BACKWARD = """
DROP TRIGGER signoff_no_truncate ON oversight_batchsignoff;
DROP TRIGGER signoff_no_update_delete ON oversight_batchsignoff;
DROP POLICY signoff_insert ON oversight_batchsignoff;
DROP POLICY signoff_read ON oversight_batchsignoff;
ALTER TABLE oversight_batchsignoff DISABLE ROW LEVEL SECURITY;
GRANT UPDATE, DELETE ON oversight_batchsignoff TO gj_app;
DROP TRIGGER flag_no_truncate ON oversight_batchflag;
DROP TRIGGER flag_no_update_delete ON oversight_batchflag;
DROP POLICY flag_insert ON oversight_batchflag;
DROP POLICY flag_read ON oversight_batchflag;
ALTER TABLE oversight_batchflag DISABLE ROW LEVEL SECURITY;
GRANT UPDATE, DELETE ON oversight_batchflag TO gj_app;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("oversight", "0002_rls_and_append_only"),
        ("positions", "0002_one_position_per_area"),
        ("reasons", "0002_seed_defaults"),
        ("core", "0002_append_only_guard"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("flagged_by", models.CharField(max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flag",
                        to="oversight.batchitem",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="positions.position",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="reasons.reasoncode"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BatchSignOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("signed_by", models.CharField(max_length=12)),
                ("otp_verified_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sign_off",
                        to="oversight.oversightbatch",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="positions.position",
                    ),
                ),
            ],
        ),
        migrations.RunSQL(sql=FORWARD, reverse_sql=BACKWARD),
    ]
