# Generated by Django 5.2.17 on 2026-09-29 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="level",
        ),
        migrations.AlterField(
            model_name="position",
            name="area",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="position",
                to="positions.area",
            ),
        ),
    ]
