# Generated by Django 5.2.17 on 2026-10-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReasonCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("OFFICER_REJECTION", "Officer rejection"),
                            ("BUYER_REJECTION", "Buyer rejection"),
                            ("SUPERINTENDENT_FLAG", "Superintendent flag"),
                        ],
                        max_length=24,
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=200)),
                ("requires_text", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("kind", "code"), name="unique_reason_per_kind"),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "kind__in",
                                ["OFFICER_REJECTION", "BUYER_REJECTION", "SUPERINTENDENT_FLAG"],
                            )
                        ),
                        name="reason_kind_valid",
                    ),
                ],
            },
        ),
    ]
