# Generated by Django 5.2.17 on 2026-10-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RuleChangeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("NEW_LICENCE_TYPE", "New licence type"),
                            ("RULE_VERSION", "New rule version"),
                            ("APPROVAL_THRESHOLD", "New approval threshold"),
                        ],
                        max_length=32,
                    ),
                ),
                ("payload", models.JSONField()),
                ("justification", models.TextField()),
                ("drafted_by", models.CharField(max_length=12)),
                ("drafted_role", models.CharField(max_length=32)),
                ("drafted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="SUBMITTED",
                        max_length=16,
                    ),
                ),
                ("decided_by", models.CharField(blank=True, max_length=12)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("applied_ref", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kind__in", ["NEW_LICENCE_TYPE", "RULE_VERSION", "APPROVAL_THRESHOLD"])
                        ),
                        name="proposal_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["SUBMITTED", "APPROVED", "REJECTED", "WITHDRAWN"])
                        ),
                        name="proposal_status_valid",
                    ),
                ],
            },
        ),
    ]
