# Generated by Django 5.2.17 on 2026-09-29 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LicenceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Substance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "unit",
                    models.CharField(choices=[("L", "Litres"), ("KG", "Kilograms")], max_length=4),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubstanceClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="LicenceTypeRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "licence_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules",
                        to="catalogue.licencetype",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogue.substance",
                    ),
                ),
                (
                    "substance_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogue.substanceclass",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="substance",
            name="substance_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="substances",
                to="catalogue.substanceclass",
            ),
        ),
        migrations.CreateModel(
            name="LicenceTypeRuleVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("may_buy", models.BooleanField()),
                ("may_sell", models.BooleanField()),
                ("may_transport", models.BooleanField()),
                ("max_stock_qty", models.DecimalField(decimal_places=3, max_digits=12)),
                ("max_per_transaction_qty", models.DecimalField(decimal_places=3, max_digits=12)),
                ("validity_months", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=64)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="catalogue.licencetyperule",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("rule", "version"), name="unique_rule_version"),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_per_transaction_qty__gt", 0), ("max_stock_qty__gt", 0)
                        ),
                        name="rule_limits_positive",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="licencetyperule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("substance__isnull", False), ("substance_class__isnull", True)),
                    models.Q(("substance__isnull", True), ("substance_class__isnull", False)),
                    _connector="OR",
                ),
                name="rule_exactly_one_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="licencetyperule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("substance__isnull", False)),
                fields=("licence_type", "substance"),
                name="one_rule_per_type_and_substance",
            ),
        ),
        migrations.AddConstraint(
            model_name="licencetyperule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("substance_class__isnull", False)),
                fields=("licence_type", "substance_class"),
                name="one_rule_per_type_and_class",
            ),
        ),
    ]
