# Generated by Django 5.2.17 on 2026-09-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0003_rule_version_trigger"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="licencetyperuleversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("validity_months__gt", 0)), name="rule_validity_positive"
            ),
        ),
    ]
