# Generated by Django 5.2.17 on 2026-10-01 10:04

import django.db.models.deletion
from django.db import migrations, models

import transactions.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogue", "0004_rule_validity_positive"),
        ("licensing", "0005_licence_status_valid"),
        ("positions", "0002_one_position_per_area"),
        ("reasons", "0002_seed_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=transactions.models.generate_reference,
                        editable=False,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("seller_gstin_index", models.CharField(max_length=64)),
                ("buyer_gstin_index", models.CharField(max_length=64)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(max_length=4)),
                ("transporter_name_encrypted", models.TextField()),
                ("transporter_id_encrypted", models.TextField()),
                ("vehicle_number_encrypted", models.TextField()),
                ("route", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AWAITING_BUYER", "Waiting for the buyer"),
                            ("AWAITING_OFFICER", "Waiting for the officer"),
                            ("APPROVED", "Approved"),
                            ("REJECTED_BY_BUYER", "Rejected by the buyer"),
                            ("REJECTED_BY_OFFICER", "Rejected by the officer"),
                            ("CANCELLED", "Cancelled by the seller"),
                        ],
                        default="AWAITING_BUYER",
                        max_length=24,
                    ),
                ),
                ("created_by", models.CharField(max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer_licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="licensing.licence",
                    ),
                ),
                (
                    "designated_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="positions.position",
                    ),
                ),
                (
                    "seller_licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="licensing.licence",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalogue.substance"
                    ),
                ),
                (
                    "superintendent_position",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="positions.position",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[("BUYER", "Buyer"), ("OFFICER", "Officer"), ("SELLER", "Seller")],
                        max_length=8,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("CONFIRM", "Confirmed"),
                            ("APPROVE", "Approved"),
                            ("REJECT", "Rejected"),
                            ("CANCEL", "Cancelled"),
                        ],
                        max_length=8,
                    ),
                ),
                ("actor_user_id", models.CharField(max_length=12)),
                ("comment", models.TextField(blank=True)),
                ("otp_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="positions.position",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reasons.reasoncode",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="transactions.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="transaction_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "AWAITING_BUYER",
                            "AWAITING_OFFICER",
                            "APPROVED",
                            "REJECTED_BY_BUYER",
                            "REJECTED_BY_OFFICER",
                            "CANCELLED",
                        ],
                    )
                ),
                name="transaction_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("seller_gstin_index", models.F("buyer_gstin_index")), _negated=True
                ),
                name="transaction_not_self",
            ),
        ),
    ]
