# Generated by Django 5.2.17 on 2026-10-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0004_rule_validity_positive"),
        ("licensing", "0005_licence_status_valid"),
        ("positions", "0002_one_position_per_area"),
        ("transactions", "0003_superintendent_required"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["seller_gstin_index", "status", "decided_at"],
                name="tx_seller_status_decided",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["buyer_gstin_index"], name="tx_buyer"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["superintendent_position", "status", "decided_at"],
                name="tx_super_status_decided",
            ),
        ),
    ]
