# Generated by Django 5.2.17 on 2026-09-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("actor", models.CharField(blank=True, max_length=64)),
                ("action", models.CharField(max_length=64)),
                ("subject_type", models.CharField(blank=True, max_length=64)),
                ("subject_id", models.CharField(blank=True, max_length=64)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(default=dict)),
                ("prev_hash", models.CharField(max_length=64)),
                ("hash", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "db_table": "audit_auditevent",
            },
        ),
        migrations.CreateModel(
            name="AuditChainHead",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False),
                ),
                ("last_hash", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "audit_auditchainhead",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="audit_head_single_row"
                    )
                ],
            },
        ),
    ]
